"use client";

import { Button } from "@/components/ui/button";
import { useLoc } from "@/lib/i18n/use-i18n";
import { creators } from "@/lib/mock/creators";
import { Check, ChevronRight, FileSpreadsheet, FolderPlus, Pencil, Plus, Search, Upload, Users, X } from "lucide-react";
import { useRef, useState } from "react";

const L = {
  groups: { zh: "达人分组", en: "Creator groups" }, defaultGroup: { zh: "默认分组", en: "Default group" }, create: { zh: "新建分组", en: "New group" }, groupName: { zh: "分组名称", en: "Group name" }, renameHint: { zh: "点击名称即可修改", en: "Click the name to rename it" }, members: { zh: "位达人", en: "creators" }, addCreators: { zh: "添加达人", en: "Add creators" }, upload: { zh: "批量上传", en: "Upload list" }, search: { zh: "搜索当前分组达人", en: "Search this group" }, empty: { zh: "这个分组还没有达人", en: "No creators in this group yet" }, emptyHint: { zh: "手动添加达人，或上传 Excel 名单进行匹配。", en: "Add creators manually or upload an Excel list to match." }, selectCreators: { zh: "从达人库添加", en: "Add from creator library" }, done: { zh: "添加到分组", en: "Add to group" }, cancel: { zh: "取消", en: "Cancel" }, matchTitle: { zh: "名单匹配完成", en: "List matching complete" }, matchCopy: { zh: "已从文件中识别并匹配到达人，可继续查看或补充添加。", en: "Creators were matched from your file and added to this group." }, uploaded: { zh: "已上传", en: "Uploaded" }, platform: { zh: "平台", en: "Platform" }, followers: { zh: "粉丝量", en: "Followers" }, engagement: { zh: "互动率", en: "Engagement" }, collabs: { zh: "历史合作", en: "Past collaborations" },
} as const;

type Group = { id: string; name: string; creatorIds: string[] };

export function PrivateCreatorGroups() {
  const l = useLoc(); const inputRef = useRef<HTMLInputElement>(null);
  const [groups, setGroups] = useState<Group[]>([{ id: "default", name: l(L.defaultGroup), creatorIds: creators.slice(0, 3).map((creator) => creator.id) }]);
  const [activeId, setActiveId] = useState("default"); const [q, setQ] = useState(""); const [pickerOpen, setPickerOpen] = useState(false); const [picked, setPicked] = useState<string[]>([]); const [uploadName, setUploadName] = useState("");
  const active = groups.find((group) => group.id === activeId) ?? groups[0];
  const members = creators.filter((creator) => {
    const matchesQuery = !q || `${creator.name} ${creator.handle}`.toLowerCase().includes(q.toLowerCase());
    return active.creatorIds.includes(creator.id) && matchesQuery;
  });
  const rename = (name: string) => setGroups((all) => all.map((group) => group.id === active.id ? { ...group, name } : group));
  const addGroup = () => { const id = `group-${Date.now()}`; setGroups((all) => [...all, { id, name: l({ zh: "新分组", en: "New group" }), creatorIds: [] }]); setActiveId(id); setUploadName(""); };
  const addPicked = () => { setGroups((all) => all.map((group) => group.id === active.id ? { ...group, creatorIds: Array.from(new Set([...group.creatorIds, ...picked])) } : group)); setPicked([]); setPickerOpen(false); };
  const upload = (file?: File) => { if (!file) return; setGroups((all) => all.map((group) => group.id === active.id ? { ...group, creatorIds: Array.from(new Set([...group.creatorIds, ...creators.slice(3, 6).map((creator) => creator.id)])) } : group)); setUploadName(file.name); };
  return <section className="mt-6"><div className="flex flex-wrap items-center gap-2">{groups.map((group) => <button key={group.id} onClick={() => { setActiveId(group.id); setUploadName(""); }} className={`flex items-center gap-2 rounded-full border px-3 py-1.5 text-[11px] font-semibold transition-colors ${group.id === active.id ? "border-brand/25 bg-soft-pink text-brand" : "border-border bg-white text-slate hover:border-brand/25"}`}><span className="max-w-[140px] truncate">{group.name}</span><span className="rounded-full bg-white/80 px-1.5 py-0.5 text-[9px] text-muted">{group.creatorIds.length}</span></button>)}<button onClick={addGroup} className="flex h-8 items-center gap-1 rounded-full border border-dashed border-border px-3 text-[11px] font-semibold text-brand hover:bg-soft-pink"><Plus className="h-3.5 w-3.5" />{l(L.create)}</button></div>
    <div className="mt-5 flex flex-wrap items-center gap-3"><div className="min-w-[200px] flex-1"><div className="flex items-center gap-2"><input value={active.name} onChange={(event) => rename(event.target.value)} className="w-full max-w-[360px] border-0 bg-transparent p-0 text-[20px] font-bold tracking-[-0.025em] text-navy outline-none" /><Pencil className="h-3.5 w-3.5 text-muted" /></div><p className="mt-1 text-[10px] text-muted">{active.creatorIds.length} {l(L.members)} · {l(L.renameHint)}</p></div><Button size="sm" variant="outline" onClick={() => setPickerOpen((open) => !open)}><Plus className="h-3.5 w-3.5" />{l(L.addCreators)}</Button><Button size="sm" onClick={() => inputRef.current?.click()}><Upload className="h-3.5 w-3.5" />{l(L.upload)}</Button><input ref={inputRef} onChange={(event) => upload(event.target.files?.[0])} accept=".xlsx,.xls,.csv" type="file" className="hidden" /></div>
    {uploadName && <div className="mt-3 flex items-center gap-2 rounded-[9px] bg-soft-teal/45 px-3 py-2 text-[10px] text-teal-text"><FileSpreadsheet className="h-3.5 w-3.5" /><strong>{uploadName}</strong><span className="text-slate">· {l(L.matchTitle)}</span><Check className="ml-auto h-3.5 w-3.5" /></div>}
    {pickerOpen && <div className="mt-4 rounded-[11px] border border-brand/20 bg-soft-pink/20 p-3"><div className="grid gap-2 sm:grid-cols-3">{creators.map((creator) => { const selected = picked.includes(creator.id); return <button key={creator.id} onClick={() => setPicked((ids) => selected ? ids.filter((id) => id !== creator.id) : [...ids, creator.id])} className={`flex items-center gap-2 rounded-[8px] border p-2 text-left ${selected ? "border-brand bg-white" : "border-border bg-white/70"}`}><span className={`flex h-4 w-4 items-center justify-center rounded border ${selected ? "border-brand bg-brand text-white" : "border-border bg-white"}`}>{selected && <Check className="h-3 w-3" />}</span><img src={creator.avatar} alt="" className="h-6 w-6 rounded-full" /><span className="truncate text-[10px] font-semibold text-ink">{creator.name}</span></button>})}</div><div className="mt-3 flex justify-end gap-2"><Button size="sm" variant="ghost" onClick={() => setPickerOpen(false)}>{l(L.cancel)}</Button><Button size="sm" disabled={!picked.length} onClick={addPicked}>{l(L.done)}</Button></div></div>}
    <div className="mt-4 flex h-10 items-center rounded-[9px] border border-border bg-page px-3"><Search className="h-4 w-4 text-muted" /><input value={q} onChange={(event) => setQ(event.target.value)} placeholder={l(L.search)} className="ml-2 w-full bg-transparent text-[11px] outline-none placeholder:text-muted" /></div>
    {members.length ? <div className="mt-3 overflow-hidden rounded-[11px] border border-border"><table className="w-full text-left"><thead className="bg-page text-[9px] font-semibold uppercase tracking-wider text-muted"><tr><th className="px-4 py-3">{l({ zh: "达人", en: "Creator" })}</th><th className="px-3 py-3">{l(L.platform)}</th><th className="px-3 py-3 text-right">{l(L.followers)}</th><th className="px-4 py-3 text-right">{l(L.engagement)}</th><th className="px-4 py-3 text-right">{l(L.collabs)}</th></tr></thead><tbody className="divide-y divide-border">{members.map((creator) => <tr key={creator.id}><td className="px-4 py-3"><div className="flex items-center gap-2.5"><img src={creator.avatar} alt="" className="h-8 w-8 rounded-full object-cover" /><div><div className="text-[11px] font-semibold text-ink">{creator.name}</div><div className="text-[9px] text-muted">{creator.handle}</div></div></div></td><td className="px-3 py-3 text-[11px] text-slate">{creator.platform}</td><td className="px-3 py-3 text-right text-[11px] font-medium text-ink">{Math.round(creator.followers / 1000)}K</td><td className="px-4 py-3 text-right text-[11px] text-ink">{creator.engagement}%</td><td className="px-4 py-3 text-right text-[11px] text-slate">{creator.collaborations ?? 0}</td></tr>)}</tbody></table></div> : <div className="mt-3 flex min-h-[230px] flex-col items-center justify-center rounded-[11px] border border-dashed border-border bg-page/40 text-center"><Users className="h-7 w-7 text-muted" /><div className="mt-3 text-[13px] font-semibold text-ink">{l(L.empty)}</div><p className="mt-1 text-[11px] text-muted">{l(L.emptyHint)}</p></div>}
  </section>;
}

function LegacyPrivateCreatorGroups() {
  const l = useLoc(); const fileInput = useRef<HTMLInputElement>(null);
  const [groups, setGroups] = useState<Group[]>([{ id: "default", name: l(L.defaultGroup), creatorIds: creators.slice(0, 3).map((creator) => creator.id) }]);
  const [activeId, setActiveId] = useState("default"); const [q, setQ] = useState(""); const [pickerOpen, setPickerOpen] = useState(false); const [picked, setPicked] = useState<string[]>([]); const [uploadName, setUploadName] = useState("");
  const active = groups.find((group) => group.id === activeId) ?? groups[0];
  const memberCreators = creators.filter((creator) => active.creatorIds.includes(creator.id) && (!q || `${creator.name} ${creator.handle}`.toLowerCase().includes(q.toLowerCase())));
  function rename(name: string) { setGroups((all) => all.map((group) => group.id === active.id ? { ...group, name } : group)); }
  function addGroup() { const id = `group-${Date.now()}`; setGroups((all) => [...all, { id, name: l({ zh: "新分组", en: "New group" }), creatorIds: [] }]); setActiveId(id); setUploadName(""); }
  function addSelected() { setGroups((all) => all.map((group) => group.id === active.id ? { ...group, creatorIds: Array.from(new Set([...group.creatorIds, ...picked])) } : group)); setPicked([]); setPickerOpen(false); }
  function uploadList(file?: File) { if (!file) return; const matched = creators.slice(3, 6).map((creator) => creator.id); setGroups((all) => all.map((group) => group.id === active.id ? { ...group, creatorIds: Array.from(new Set([...group.creatorIds, ...matched])) } : group)); setUploadName(file.name); }
  return <div className="grid min-h-[600px] overflow-hidden rounded-[16px] border border-border bg-white lg:grid-cols-[250px_minmax(0,1fr)]">
    <aside className="border-b border-border bg-page/45 p-4 lg:border-b-0 lg:border-r"><div className="mb-4 flex items-center justify-between"><h2 className="text-[13px] font-semibold text-ink">{l(L.groups)}</h2><button onClick={addGroup} className="flex h-7 w-7 items-center justify-center rounded-[7px] bg-white text-brand hover:bg-soft-pink"><FolderPlus className="h-4 w-4" /></button></div><div className="space-y-1">{groups.map((group) => <button key={group.id} onClick={() => { setActiveId(group.id); setUploadName(""); }} className={`flex w-full items-center gap-2 rounded-[9px] px-3 py-2.5 text-left ${active.id === group.id ? "bg-white text-brand shadow-sm" : "text-slate hover:bg-white"}`}><Users className="h-3.5 w-3.5" /><span className="min-w-0 flex-1 truncate text-[11px] font-semibold">{group.name}</span><span className="rounded-full bg-page px-1.5 py-0.5 text-[9px] text-muted">{group.creatorIds.length}</span></button>)}</div><button onClick={addGroup} className="mt-3 flex items-center gap-2 px-3 py-2 text-[11px] font-semibold text-brand hover:text-brand-hover"><Plus className="h-3.5 w-3.5" />{l(L.create)}</button></aside>
    <section className="min-w-0 p-5 sm:p-6"><div className="flex flex-wrap items-start gap-3"><div className="min-w-[220px] flex-1"><div className="flex items-center gap-2"><input value={active.name} onChange={(event) => rename(event.target.value)} className="w-full border-0 bg-transparent p-0 text-[20px] font-bold tracking-[-0.025em] text-navy outline-none" /><Pencil className="h-3.5 w-3.5 text-muted" /></div><p className="mt-1 text-[10px] text-muted">{l(L.renameHint)} · {active.creatorIds.length} {l(L.members)}</p></div><Button size="sm" variant="outline" onClick={() => setPickerOpen(true)}><Plus className="h-3.5 w-3.5" />{l(L.addCreators)}</Button><Button size="sm" onClick={() => fileInput.current?.click()}><Upload className="h-3.5 w-3.5" />{l(L.upload)}</Button><input ref={fileInput} onChange={(event) => uploadList(event.target.files?.[0])} accept=".xlsx,.xls,.csv" type="file" className="hidden" /></div>
      {uploadName && <div className="mt-4 flex flex-wrap items-center gap-3 rounded-[10px] border border-teal/25 bg-soft-teal/40 px-3.5 py-3"><span className="flex h-7 w-7 items-center justify-center rounded-[7px] bg-white text-teal-text"><FileSpreadsheet className="h-4 w-4" /></span><div className="min-w-[180px] flex-1"><div className="text-[11px] font-semibold text-ink">{l(L.matchTitle)} · {uploadName}</div><div className="mt-0.5 text-[10px] text-slate">{l(L.matchCopy)}</div></div><span className="flex items-center gap-1 text-[10px] font-semibold text-teal-text"><Check className="h-3.5 w-3.5" />{l(L.uploaded)}</span></div>}
      <div className="mt-5 flex h-10 items-center rounded-[9px] border border-border bg-page px-3"><Search className="h-4 w-4 text-muted" /><input value={q} onChange={(event) => setQ(event.target.value)} placeholder={l(L.search)} className="ml-2 w-full bg-transparent text-[11px] outline-none placeholder:text-muted" /></div>
      {memberCreators.length ? <div className="mt-4 overflow-hidden rounded-[11px] border border-border"><table className="w-full text-left"><thead className="bg-page text-[9px] font-semibold uppercase tracking-wider text-muted"><tr><th className="px-4 py-3">{l({ zh: "达人", en: "Creator" })}</th><th className="px-3 py-3">{l(L.platform)}</th><th className="px-3 py-3 text-right">{l(L.followers)}</th><th className="px-4 py-3 text-right">{l(L.engagement)}</th><th className="px-4 py-3 text-right">{l(L.collabs)}</th></tr></thead><tbody className="divide-y divide-border">{memberCreators.map((creator) => <tr key={creator.id}><td className="px-4 py-3"><div className="flex items-center gap-2.5"><img src={creator.avatar} alt="" className="h-8 w-8 rounded-full object-cover" /><div><div className="text-[11px] font-semibold text-ink">{creator.name}</div><div className="text-[9px] text-muted">{creator.handle}</div></div></div></td><td className="px-3 py-3 text-[11px] text-slate">{creator.platform}</td><td className="px-3 py-3 text-right text-[11px] font-medium text-ink">{Math.round(creator.followers / 1000)}K</td><td className="px-4 py-3 text-right text-[11px] text-ink">{creator.engagement}%</td><td className="px-4 py-3 text-right text-[11px] text-slate">{creator.collaborations ?? 0}</td></tr>)}</tbody></table></div> : <div className="mt-4 flex min-h-[270px] flex-col items-center justify-center rounded-[11px] border border-dashed border-border bg-page/40 text-center"><Users className="h-7 w-7 text-muted" /><div className="mt-3 text-[13px] font-semibold text-ink">{l(L.empty)}</div><p className="mt-1 text-[11px] text-muted">{l(L.emptyHint)}</p></div>}
      {pickerOpen && <div className="mt-4 rounded-[11px] border border-brand/20 bg-soft-pink/25 p-4"><div className="mb-3 flex items-center justify-between"><div className="text-[12px] font-semibold text-ink">{l(L.selectCreators)}</div><button onClick={() => setPickerOpen(false)} className="text-muted"><X className="h-4 w-4" /></button></div><div className="grid gap-2 sm:grid-cols-2">{creators.map((creator) => { const selected = picked.includes(creator.id); return <button key={creator.id} onClick={() => setPicked((ids) => selected ? ids.filter((id) => id !== creator.id) : [...ids, creator.id])} className={`flex items-center gap-2 rounded-[8px] border p-2 text-left ${selected ? "border-brand bg-white" : "border-border bg-white/70"}`}><span className={`flex h-4 w-4 items-center justify-center rounded border ${selected ? "border-brand bg-brand text-white" : "border-border bg-white"}`}>{selected && <Check className="h-3 w-3" />}</span><img src={creator.avatar} alt="" className="h-7 w-7 rounded-full" /><span className="text-[10px] font-semibold text-ink">{creator.name}</span></button>})}</div><div className="mt-3 flex justify-end gap-2"><Button size="sm" variant="ghost" onClick={() => setPickerOpen(false)}>{l(L.cancel)}</Button><Button size="sm" disabled={!picked.length} onClick={addSelected}>{l(L.done)}<ChevronRight className="h-3.5 w-3.5" /></Button></div></div>}
    </section>
  </div>;
}
